### PR TITLE
Optional filter for the object_attributes.source

### PR DESCRIPTION
**Pull request by xMAC94x**
It seems like schedules don't have all the variables propagated correctly that normal builds have.

An alternative filter would search for the object_attributes.source which is set to "schedule" for scheduled builds.
https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#pipeline-events

This however would only scale for a single schedule (which we currently have).

An alternative would be to search for a specific job_name, e.g. "release-nightly" or a specific "stage" to be present in order to accept the webhook

### CODE REVIEW

**Comment by Songtronix** [comment]
Then remove the variables and this and we can use the stage to determine to pull it. This check is already working. All this is a temporary way anyway as 0.5 will introduce an api to upload to specific channels etc.

**Comment by xMAC94x** [comment]
I can remove the variable filter as its basically unused now.
However i am still not sure how the stage will work out to distinguish a normal pipeline and a scheduled one?

**Comment by Songtronix** [comment]
> 
> 
> I can remove the variable filter as its basically unused now.
> However i am still not sure how the stage will work out to distinguish a normal pipeline and a scheduled one?

we have a different stage which only gets triggered by the scheduled pipeline

**Comment by Songtronix** [comment]
Sorry but closing this in favor of the above described way. Any wishes/ideas on how exactly the api to make releases from CI should be hit me up.

**Pull request closed without merging**
